version: "3.8"

services:
    cache:
        image: redis:latest
        ports:
            - target: 6379
        networks:
            - backend

    server:
        image: pxseu/pxseu-dot-com_api:latest
        build: .
        environment:
            - REDIS_HOST=cache
            - REDIS_PORT=6379
            - ENV_PATH=/run/secrets/PXSEU_API_ENV_FILE
        secrets:
            - PXSEU_API_ENV_FILE
        ports:
            - target: 80
        depends_on:
            - cache
        networks:
            - backend
        deploy:
            replicas: 4
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 20s
            rollback_config:
                parallelism: 0
                order: stop-first
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
        healthcheck:
            test: curl --fail http://localhost/health || exit 1
            interval: 10s
            retries: 5
            start_period: 5s
            timeout: 10s

networks:
    backend:
        name: pxseu_api_swarm
        driver: overlay

secrets: # top level secrets block
    PXSEU_API_ENV_FILE:
        external: true
